//https://github.com/stevep99/seniply/blob/master/downloads/qmk/redox/rev1/redox-seniply.json
#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define LSFT(KC_GRV)  SFT_GRV
#define LSFT(KC_NUHS) SFT_HSH
#define LSFT(KC_NUBS) SFT_BSL
#define LALT(KC_LEFT) ALT_LFT
#define LCTL(KC_F)    CTL_F
#define LALT(KC_RGHT) ALT_RGT
#define OSM(MOD_LALT) OS_LALT
#define OSM(MOD_LSFT) OS_LSFT
#define OSM(MOD_LCTL) OS_LCTL
#define OSM(MOD_RALT) OS_RALT
#define LCTL(KC_Z)    CTL_Z
#define LCTL(KC_X)    CTL_X
#define LCTL(KC_C)    CTL_C
#define LCTL(KC_V)    CTL_V
#define LSA(KC_LEFT)  LSA_LFT
#define RCS(KC_F)     RCS_F
#define LSA(KC_RGHT)  LSA_RGT
#define OSM(MOD_LGUI) OS_LGUI
#define RCS(KC_Z)     RCS_Z
#define RCS(KC_X)     RCS_X
#define RCS(KC_C)     RCS_C
#define LSFT(KC_TAB)  SFT_TAB
#define RCS(KC_V)     RCS_V
RCS(KC_Z), RCS(KC_X), RCS(KC_C), LSFT(KC_TAB), RCS(KC_V)
RCS_Z, RCS_X, RCS_C, SFT_TAB, RCS_V

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
        KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                                        KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    KC_MINS,\
        KC_TAB,  KC_Q,    KC_W,    KC_F,    KC_P,    KC_B,    KC_NO,                     KC_NO,   KC_J,    KC_L,    KC_U,    KC_Y,    KC_QUOT, KC_EQL, \
        KC_LGUI, KC_A,    KC_R,    KC_S,    KC_T,    KC_G,    KC_BSLS,                   KC_BSPC, KC_M,    KC_N,    KC_E,    KC_I,    KC_O,    KC_ENT, \
        KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_D,    KC_V,    KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_K,    KC_H,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,\
        KC_NO,   KC_LCTL, KC_LALT, MO(3),            KC_LSFT, MO(4),   KC_LGUI, KC_ENT,  MO(2),    KC_SPC,          MO(1),   KC_RALT, KC_RCTL, KC_NO   \
    ),
    [1] = LAYOUT(
        _______, KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                                       KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,   KC_F11,\
        _______, KC_EXLM, KC_AT,   KC_HASH, KC_DLR,  KC_PERC, _______,                   _______, KC_EQL,  KC_7,    KC_8,    KC_9,    KC_PLUS,  KC_F12,\
        _______, KC_SCLN, KC_COLN, KC_LCBR, KC_LPRN, KC_LBRC, _______,                   _______, KC_ASTR, KC_4,    KC_5,    KC_6,    KC_MINS,  KC_PENT,\
        _______, KC_CIRC, KC_AMPR, KC_RCBR, KC_RPRN, KC_RBRC, _______, _______, _______, _______, KC_0,    KC_1,    KC_2,    KC_3,    KC_SLSH,  KC_NO,\
        _______, _______, _______, MO(4),            MO(2),   _______, _______, _______, KC_NO,   KC_NO,            _______, KC_NO,   KC_NO,   KC_NO\
    ),
    [2] = LAYOUT(
        _______, _______, _______, _______, _______, _______,                                     _______, _______, _______, _______, _______, _______,\
        KC_NO,   KC_MUTE, KC_VOLD, KC_VOLU, KC_MPRV, KC_MNXT, _______,                   _______, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  \
        KC_NO,   KC_GRV,  SFT_GRV, KC_NUHS, SFT_HSH, KC_MSTP, _______,                   _______, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_UNDS, KC_NO,  \
        KC_NO,   KC_NUBS, SFT_BSL, KC_NO,   KC_MPLY, KC_MSTP, _______, _______, _______, KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  \
        KC_NO,   KC_NO,   KC_NO,   KC_NO,            _______, _______, _______, _______, _______, _______,          _______, KC_NO,   KC_NO,   KC_NO   \
    ),
    [3] = LAYOUT(
        RESET,   KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                                       KC_F6,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  RESET,  \
        RGB_TOG, KC_ESC,  ALT_LFT, CTL_F,   ALT_RGT, KC_INS,  KC_NO,                     KC_NO,   KC_PGUP, KC_HOME, KC_UP,   KC_END,  KC_CAPS, BL_TOGG,\
        RGB_MOD, OS_LALT, KC_LGUI, OS_LSFT, OS_LCTL, OS_RALT, KC_NO,                     KC_NO,   KC_PGDN, KC_LEFT, KC_DOWN, KC_RGHT, KC_DEL,  BL_STEP,\
        KC_NO,   CTL_Z,   CTL_X,   CTL_C,   KC_TAB,  CTL_V,   _______, KC_NO,   KC_NO,   _______, KC_ENT,  KC_BSPC, KC_RCTL, KC_LALT, KC_APP,  BL_BRTG,\
        KC_NO,   KC_NO,   KC_NO,   KC_NO,            KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_ENT,           MO(4),   KC_NO,   KC_NO,   KC_NO   \
    ),
    [4] = LAYOUT(
        KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,                                       KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,  \
        KC_NO,   KC_NO,   LSA_LFT, RCS_F,   LSA_RGT, KC_NO,   KC_NO,                     KC_NO,   KC_NO,   KC_F7,   KC_F8,   KC_F9,   KC_F10,  KC_NO,  \
        KC_NO,   OS_LALT, OS_LGUI, OS_LSFT, OS_LCTL, OS_RALT, KC_NO,                     KC_NO,   KC_NO,   KC_F4,   KC_F5,   KC_F6,   KC_F11,  KC_NO,  \
        KC_NO,   RCS_Z,   RCS_X,   RCS_C,   SFT_TAB, RCS_V,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_F1,   KC_F2,   KC_F3,   KC_F12,  KC_NO,  \
        KC_NO,   KC_NO,   KC_NO,   _______,          KC_NO,   _______, KC_NO,   KC_NO,   _______, KC_NO,            KC_NO,   KC_NO,   KC_NO,   KC_NO\
    )
};